crates/ere-jolt/src/lib.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, crates/ere-sp1/src/lib.rs, crates/zkvm-interface/src/lib.rs
Currently CPU proving is the default, this allows zkVM implementations to switch between cpu and gpu proving based on the ProverResourceType enum
=> feat: allow callers to specify GPU proving

crates/ere-jolt/src/lib.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, crates/ere-sp1/src/lib.rs, crates/zkvm-interface/src/lib.rs
Main benefit is that the `zkVM` trait is no longer parametrized by Compiler, so we can have a heterogenous list of `dyn zkVM` that have different programs and also `zkVM` is now object safe
=> chore: move `new` out of zkvm-interface

crates/ere-jolt/src/error.rs, crates/ere-jolt/src/lib.rs, crates/ere-openvm/src/error.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/error.rs, crates/ere-pico/src/lib.rs, crates/ere-sp1/src/error.rs, crates/ere-sp1/src/lib.rs, crates/zkvm-interface/src/lib.rs
Rationale is the same for removing Compiler trait from the zkVM trait -- so that we can do something like `Vec<dyn zkVM>`
It may be possible that we bring this back, but for now this seems to be the best way to expose multiple zkVMs for the end users
=> chore: concerete zkVM Error

crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, crates/ere-risczero/src/lib.rs, crates/ere-sp1/src/lib.rs, crates/ere-zisk/src/lib.rs, crates/zkvm-interface/src/reports.rs
This PR adds a new field `execution_duration` to `ProgramExecutionReport`. This allows for later analytics around `cycles/second` or simply raw-zkVM raw execution performance.
=> zkvm-interface: add execution duration

Cargo.lock, crates/ere-openvm/Cargo.toml, scripts/sdk_installers/install_openvm_sdk.sh, tests/openvm/compile/basic/Cargo.toml
FIx the [openvm's CI issue](https://github.com/eth-applied-research-group/ere/actions/runs/15441186422/job/43459158563).
=> fix: pin `openvm` version and upgrade the latest tag

crates/ere-sp1/src/lib.rs
This PR switches SP1 from [Core proof type](https://docs.succinct.xyz/docs/sp1/generating-proofs/proof-types#core-default) to[ Compressed proof type](https://docs.succinct.xyz/docs/sp1/generating-proofs/proof-types#compressed).
I wouldn't think of generalizing the API to support multiple options until we incorporate Hypercube since might be wasted effort. I think using compressed proofs is a fair choice today.
=> sp1: use compressed proofs

crates/ere-risczero/src/lib.rs
While doing some early testing of `zkevm-benchmark-workload` tracking proof sizes, I saw that Risc0 proofs were >300MiB, which signaled a similar misconfig as done for SP1 in https://github.com/eth-act/ere/pull/36.
With this change, now proofs sizes are 0.21MiB.
[Risc0 docs here](https://dev.risczero.com/api/generating-proofs/proving-options), in particular the _Tip_ highlight.
=> risc0: generate succinct proofs

.github/workflows/check_pico_image.yml, Cargo.lock, Cargo.toml, crates/build-utils/Cargo.toml, crates/build-utils/src/lib.rs, crates/ere-jolt/Cargo.toml, crates/ere-jolt/build.rs, crates/ere-jolt/src/lib.rs, crates/ere-openvm/Cargo.toml, crates/ere-openvm/build.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/Cargo.toml, crates/ere-pico/build.rs, crates/ere-pico/src/lib.rs, crates/ere-risczero/Cargo.toml, crates/ere-risczero/build.rs, crates/ere-risczero/src/lib.rs, crates/ere-sp1/Cargo.toml, crates/ere-sp1/build.rs, crates/ere-sp1/src/lib.rs, crates/ere-zisk/Cargo.toml, crates/ere-zisk/build.rs, crates/ere-zisk/src/lib.rs, crates/zkvm-interface/src/lib.rs, tests/pico/compile/basic/Cargo.toml, tests/sp1/compile/basic/Cargo.toml, tests/sp1/execute/basic/Cargo.toml, tests/sp1/prove/basic/Cargo.toml
This PR adds a new mechanism that allows defining for each zkVM ere implementation:
- The name as a constant.
- The SDK version is automatically detected in the build phase.
This feature is used by `zkevm-benchmark-workload` to create a proper full name for the output results. For more information, see https://github.com/eth-act/zkevm-benchmark-workload/pull/104.
This PR is in draft mode to get early feedback. If it makes sense, it would be applied to the rest of the current zkVM implementations.
=> Add automatic name and sdk version

crates/ere-risczero/Cargo.toml, crates/zkvm-interface/src/input.rs, tests/risczero/compile/project_structure_build/Cargo.toml, tests/risczero/compile/project_structure_build/guest/Cargo.toml
This PR makes some changes to `InputItem` to support: `Debug`, `Sync`, `Send`, and `Clone`.
=> InputItem: Support extra traits

.github/workflows/rust-checks.yml, Cargo.lock, README.md, crates/ere-jolt/src/lib.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, crates/ere-risczero/src/lib.rs, crates/ere-sp1/src/compile.rs, crates/ere-sp1/src/error.rs, crates/ere-sp1/src/lib.rs, crates/ere-zisk/src/compile.rs, crates/ere-zisk/src/lib.rs, crates/zkvm-interface/src/input.rs, crates/zkvm-interface/src/lib.rs
This PR goal is to enable target guest programs to be compiled as part of a parent directory, which is beneficial for them to leverage potential parent assets. A obvious example today is compiling guest programs that are part of workspaces. 
This feature required changing the `compile` method in the `Compiler` trait:
```rust
/// Compiles the program and returns the program
///
/// # Arguments
/// * `mount_directory` - The base directory (workspace root)
/// * `guest_relative` - The relative path from mount_directory to the guest program
fn compile(mount_directory: &Path, guest_relative: &Path)
-> Result<Self::Program, Self::Error>;
```
The rest of the codebase changes are kind of downstream from here -- but I'll add some extra comments.
See how this is used in a [tentative …
=> docker: separate workspace and guest program directories

README.md, crates/zkvm-interface/src/lib.rs
Clarify that each zkVM instance is created for specific program and fix `README.md`
Resolves #43
=> Add constructor function for `trait zkVM`

Cargo.lock, Cargo.toml, crates/ere-cli/Cargo.toml, crates/ere-cli/src/main.rs, crates/ere-dockerized/src/docker.rs, crates/ere-dockerized/src/lib.rs, docker/sp1/Dockerfile
This PR mainly fixes `ere-dockerized` SP1 GPU prover, also does:
- Add `tracing_subscriber` with `EnvFilter` in `ere-cli`
- Inherit `RUST_LOG` from `ere-dockerized` to `ere-cli`
- Always use CPU to `execute` in `ere-cli`
- Add `docker` cli into SP1's base image, add flags to `docker run` to enable SP1 GPU prover service (enables Docker-out-of-Docker and host network).
=> Fix `ere-dockerized` SP1 GPU prover

Cargo.lock, Cargo.toml, crates/ere-cli/Cargo.toml, crates/ere-cli/src/lib.rs, crates/ere-cli/src/main.rs, crates/ere-cli/src/serde.rs, crates/ere-dockerized/Cargo.toml, crates/ere-dockerized/src/input.rs, crates/ere-nexus/src/lib.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/Cargo.toml, crates/ere-pico/src/lib.rs, crates/ere-risc0/src/lib.rs, crates/ere-sp1/src/lib.rs, crates/ere-zisk/src/lib.rs, crates/zkvm-interface/Cargo.toml, crates/zkvm-interface/src/input.rs, docker/cli/Dockerfile
This is required for using dockerized `risc0` (`ere-dockerized` calling `ere-cli` with feature `risc0`).
In `risc0` there are multiple way to write the input:
- `write::<T: Serialize>(obj: T)` - It serializes the object with its own serializer, used to serialize `InputItem::Object`
- `write_frame(bytes: Vec<u8>)` - It serializes it by `[bytes.len().as_le_bytes(), bytes].concat()`, use to serialize `InputItem::Bytes`
- `write_slice(bytes: Vec<u8>)` - It doesn't do extra serialization and just append the bytes to its input, not used in ere currently
Currently `ere-dockerized` needs to serialize the `InputItem::Object` to be able to pass it to `ere-cli` by file, this works for most zkVMs that doesn't do extra serialization on the `InputItem::Bytes`, but doesn't work for `risc0`.
For this PR …
=> Add `InputItem::SerializedObject`

Cargo.lock, Cargo.toml, crates/ere-cli/src/main.rs, crates/ere-dockerized/src/lib.rs, crates/ere-risc0/Cargo.toml, crates/ere-risc0/compose.yml, crates/ere-risc0/gpu_prover_agent.yml, crates/ere-risc0/sample.env, crates/ere-risc0/src/lib.rs, crates/ere-risc0/src/prove.rs, crates/ere-risc0/src/prove/bento.rs, crates/ere-risc0/src/prove/default.rs, docker/risc0/Dockerfile, scripts/install_cuda.sh, scripts/install_docker.sh, scripts/sdk_installers/install_risc0_sdk.sh
- Add script to install `cuda` for easier development
- Add script to install `docker` for easier development
- Remove `cuda` feature so we don't need feature flag to enable GPU proving
- The building time is unaffected because the cuda GPU proving is using docker (image will be built when init the `EreRisc0`)
- The `metal` feature remains optional because it increase the building time
- When the prover resource is GPU
- `EreRisc0` builds the images if it doesn't exist (tagging with Risc0's SDK version), then use docker compose to spin up the proving services
- Then send the image and input to the service for proving, and by interval (200ms) check if the proof is ready or not
- When `EreRisc0` is dropped, it shuts down the services (if not properly dropped, the services get dangling.
- In …
=> Add multi-gpu proving for risc0

.github/workflows/test-zkvm-pico.yml, .github/workflows/test-zkvm.yml, Cargo.lock, Cargo.toml, crates/ere-openvm/src/error.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, docker/cli/Dockerfile, docker/pico/Dockerfile, scripts/sdk_installers/install_openvm_sdk.sh, scripts/sdk_installers/install_pico_sdk.sh, tests/pico/basic/Cargo.toml, tests/pico/basic/rust-toolchain.toml
This PR:
- Generate OpenVM aggregation keys when installing SDK (~460MB), and reuse to avoid recomputation. 
- Add `RUSTFLAGS=-Ctarget-cpu=native` in `test_via_docker` in CI to speed up `plonky3` based prover
- Add `RUSTFLAGS=-Ctarget-cpu=native` in `ere-cli` Dockerfile to speed up `plonky3` based prover
- Upgrdae Pico to `v1.1.7` to work with `RUSTFLAGS=-Ctarget-cpu=native` (the compile failed with previous version)
The reason not adding `RUSTFLAGS=-Ctarget-cpu=native` to `.cargo/config.toml` is because the guest programs are sub-directories of this repo, which will reference it and not trivial to ignore, and [`zisk`'s compilation will complain a lot](https://github.com/eth-act/ere/actions/runs/17270878327/job/49015307931#step:6:202) (tho not really failing).
This makes the OpenVM's CI …
=> OpenVM cache pk

Cargo.lock, crates/ere-jolt/Cargo.toml, crates/ere-jolt/src/compile_stock_rust.rs, crates/ere-jolt/src/error.rs, crates/ere-jolt/src/lib.rs, crates/ere-jolt/src/template.ld, docker/jolt/Dockerfile, tests/jolt/stock_nightly_no_std/Cargo.toml, tests/jolt/stock_nightly_no_std/src/main.rs
This PR implements support for a guest program compilation to the target `riscv32im-unknown-none-elf` with stock rust compiler. It can be enabled by defining environment variable `ERE_GUEST_TOOLCHAIN=nightly` to build using rust nightly toolchain.
=> jolt: Guest program compilation with stock rust compiler.

.github/workflows/test-common.yml, crates/ere-dockerized/src/lib.rs
- Add getters for `EreDockerizedzkVM`
- Move the `build_docker_image` to `EreDockerizedCompiler::new` to be more consistent
- Fix the doc of `ere-dockerized`
- In CI add `cargo test --doc` for common crates.
=> Add getters for `EreDockerizedzkVM`

docker/base/Dockerfile.base
This PR adds `clang` to the installed packages in `ere-base`.
This is required since some dependencies in guest program require clang for building. As a concrete example, this is the case for [Ethrex guest program](https://github.com/eth-act/zkevm-benchmark-workload/pull/158).
=> Add clang to ere-base

.github/workflows/test-zkvm-jolt.yml, .github/workflows/test-zkvm-nexus.yml, .github/workflows/test-zkvm-openvm.yml, .github/workflows/test-zkvm-pico.yml, .github/workflows/test-zkvm-risc0.yml, .github/workflows/test-zkvm-sp1.yml, .github/workflows/test-zkvm.yml, Cargo.lock, Cargo.toml, README.md, crates/ere-cli/Cargo.toml, crates/ere-dockerized/src/cuda.rs, crates/ere-dockerized/src/docker.rs, crates/ere-dockerized/src/lib.rs, crates/ere-jolt/src/lib.rs, crates/ere-nexus/src/lib.rs, crates/ere-openvm/Cargo.toml, crates/ere-openvm/src/compile_stock_rust.rs, crates/ere-openvm/src/lib.rs, crates/ere-pico/src/lib.rs, crates/ere-risc0/src/lib.rs, crates/ere-sp1/src/lib.rs, crates/ere-zisk/src/lib.rs, docker/cli/Dockerfile, docker/openvm/Dockerfile, scripts/sdk_installers/install_openvm_sdk.sh, tests/openvm/basic/Cargo.toml, tests/openvm/stock_nightly_no_std/src/openvm_rt.rs
- Update `openvm` to `v1.4.0`.
- Add `cuda` feature and enabled by default in `ere-openvm`, and add support of `ProverResourceType::Gpu`
- Add feature flag `cuda` in `ere-cli` as well
- In CI add an boolean option `default_features` to conditional enable/disable default features, which includes `cuda`, to avoid needing cuda to run clippy/test.
I thin eventually we need to handle the cuda building thing on CI, otherwise I feel the building process will get more and more complicated :(
=> Add GPU proving support in `ere-openvm`

.github/workflows/test-zkvm.yml
This PR attempts to resolve #2.
In CI we detect if the Dockerfile related files changed or not, if it's not changed, we re-tag the image remotely (so no pulling/pushing). For now the related files are only the Dockerfile itself and the SDK installation script, so I think it's maintainable, but with the related files grow we probably need to find a better way to decide to rebuild or not.
If the `ere-base` and `ere-base-{zkvm}` images are reused, the CI time becomes ~12mins.
=> Reuse base image if unchanged in CI

Cargo.lock, Cargo.toml, crates/ere-risc0/src/compile_stock_rust.rs, crates/ere-risc0/src/lib.rs, docker/risc0/Dockerfile, scripts/sdk_installers/install_risc0_sdk.sh, tests/risc0/allocs_alignment/Cargo.toml, tests/risc0/basic/Cargo.toml
Upgrade `risc0-zkvm` to `3.0.3`. Also I found the dep `risc0-zkvm-platform` is unused (the `env::cycle_count` is enabled by default), so we don't need to enable its `sys-getenv` feature in `zkevm-benchmark-workload` as well (but probably need to upgrade `risc0-zkvm-platform` to `2.2.1` in `Cargo.lock` if it's not upgraded automatically)
=> Upgrade `risc0-zkvm` to `3.0.3`, also remove unused dep `risc0-zkvm-platform`

.github/workflows/test-zkvm-miden.yml, Cargo.lock, Cargo.toml, README.md, crates/ere-cli/Cargo.toml, crates/ere-cli/src/main.rs, crates/ere-miden/Cargo.toml, crates/ere-miden/build.rs, crates/ere-miden/src/compile.rs, crates/ere-miden/src/error.rs, crates/ere-miden/src/io.rs, crates/ere-miden/src/lib.rs, docker/miden/Dockerfile, tests/miden/add/add.masm, tests/miden/fib/fib.masm
I would address this PR as an initial `miden-vm` integration. One of the biggest differentiators of it with other `ere` crates is that guests are implemented in `miden assembly`. The reason for this is that compiler support for [Rust to Masm is being rolled out](https://miden.xyz/resource/blog/compiler-release-04) but not fully compatible at the moment. 
Adding a bit of context, the [client side proving benchmarks](https://github.com/privacy-ethereum/csp-benchmarks/tree/CSP-Q3-2025/zkvm) now have `ere` as its default zkVM interface. This allows us to support all `ere` zkVMs with low effort and a standardize way of interacting with them.
The `miden-vm` has client-side proving capabilities, with comparable [results](https://github.com/privacy-ethereum/csp-benchmarks/pull/32) to other zkVMs, …
=> feat: `ere-miden` 

Cargo.lock, Cargo.toml, crates/ere-dockerized/build.rs, crates/ere-pico/Cargo.toml, crates/ere-pico/build.rs, crates/ere-pico/src/client.rs, crates/ere-pico/src/compile_stock_rust.rs, crates/ere-pico/src/error.rs, crates/ere-pico/src/lib.rs, tests/pico/stock_nightly_no_std/src/pico_rt.rs
This PR:
- Copy and modify the client from https://github.com/brevis-network/pico/blob/v1.1.7/sdk/sdk/src/client.rs and remove the groth16 wrapper
- Add `PicoProofWithPublicValues` because the public values of recursive proof only contains digest of guest public values.
- Check public values digest matches in method `verify`, and returns public values from `PicoProofWithPublicValues`
This should unblock https://github.com/eth-act/zkevm-benchmark-workload/issues/173
=> Complete `ere-pico`

.github/workflows/test-zkvm-pico.yml, crates/ere-dockerized/src/lib.rs
Add the missed dockerized pico test that should be added in https://github.com/eth-act/ere/pull/139
=> Test dockerized pico

crates/ere-openvm/src/lib.rs
Switch from [`CpuSdk::execute`](https://github.com/openvm-org/openvm/blob/39ee587f0f73646e3753cb2aa5f34885d4efffe0/crates/sdk/src/lib.rs#L345) to [`CpuSdk::execute_metered_cost`](https://github.com/openvm-org/openvm/blob/39ee587f0f73646e3753cb2aa5f34885d4efffe0/crates/sdk/src/lib.rs#L396) in order to get the execution cycles along with public values.
=> Include OpenVM execution cycles count

Cargo.lock, Cargo.toml, crates/ere-compiler/Cargo.toml, crates/ere-compiler/src/main.rs, crates/ere-server/Cargo.toml, crates/ere-server/src/main.rs
In later PR we will remove the `ere-cli` and replace it with `ere-compiler` and `ere-server`.
Currently in `ere-compiler` we can select to use stock rust compiler by setting env `ERE_RUST_TOOLCHAIN`, but if there are more compilers in the future, we'd need to figure out a way to specify the guest kind.
=> Add crate `ere-compiler`
